In [1]:
import pickle
import numpy as np
import pandas as pd

pickle.dump(rf_model, open('model.pkl','wb'))
rf_model = pickle.load(open('model.pkl','rb'))
pickle.dump(classifier, open('linearreg.pkl','wb'))
pickle.dump(scaler, open('scaler.pkl','wb'))
pickle.dump(enc, open('encoder.pkl','wb'))
pickle.dump(encz, open('encoderz.pkl','wb'))

In [2]:
predict=[]
predict=['11367', '3','3','1980','Queens County','0.034581', '0.141027']
predict

['11367', '3', '3', '1980', 'Queens County', '0.034581', '0.141027']

## Boroughs

Load encoder

In [3]:
enc=pickle.load(open('encoder.pkl','rb'))

Apply encoder to create `boro_` columns

In [4]:
part_a = pd.DataFrame.from_records(
    enc.transform(np.array([[predict[4].ljust(50, " ")]])),
    columns=enc.get_feature_names(['boro'])
)

In [5]:
part_a

boro_Kings County                                        \
0                                                0.0         

   boro_New York County                                     \
0                                                0.0         

   boro_Queens County                                       \
0                                                1.0         

   boro_Richmond County                                     
0                                                0.0

## ZIP codes

In [6]:
encz=pickle.load(open('encoderz.pkl','rb'))

Apply encoder to create zip_ columns

In [7]:
part_b = pd.DataFrame.from_records(
    encz.transform(np.array([[predict[0]]])),
    columns=encz.get_feature_names(['zip'])
)

In [8]:
part_b

zip_10002  zip_10003  zip_10004  zip_10005  zip_10006  zip_10007  \
0        0.0        0.0        0.0        0.0        0.0        0.0   

   zip_10009  zip_10010  zip_10011  zip_10012  ...  zip_11426  zip_11427  \
0        0.0        0.0        0.0        0.0  ...        0.0        0.0   

   zip_11428  zip_11429  zip_11430  zip_11432  zip_11433  zip_11434  \
0        0.0        0.0        0.0        0.0        0.0        0.0   

   zip_11435  zip_11436  
0        0.0        0.0  

[1 rows x 158 columns]

In [9]:
list(part_b)

['zip_10002',
 'zip_10003',
 'zip_10004',
 'zip_10005',
 'zip_10006',
 'zip_10007',
 'zip_10009',
 'zip_10010',
 'zip_10011',
 'zip_10012',
 'zip_10013',
 'zip_10014',
 'zip_10016',
 'zip_10017',
 'zip_10018',
 'zip_10019',
 'zip_10021',
 'zip_10022',
 'zip_10023',
 'zip_10024',
 'zip_10025',
 'zip_10026',
 'zip_10027',
 'zip_10028',
 'zip_10029',
 'zip_10030',
 'zip_10031',
 'zip_10032',
 'zip_10033',
 'zip_10034',
 'zip_10035',
 'zip_10036',
 'zip_10037',
 'zip_10038',
 'zip_10039',
 'zip_10040',
 'zip_10044',
 'zip_10065',
 'zip_10075',
 'zip_10128',
 'zip_10280',
 'zip_10301',
 'zip_10302',
 'zip_10303',
 'zip_10304',
 'zip_10305',
 'zip_10306',
 'zip_10307',
 'zip_10308',
 'zip_10309',
 'zip_10310',
 'zip_10312',
 'zip_10314',
 'zip_10451',
 'zip_10452',
 'zip_10453',
 'zip_10455',
 'zip_10456',
 'zip_10457',
 'zip_10458',
 'zip_10459',
 'zip_10460',
 'zip_10461',
 'zip_10462',
 'zip_10463',
 'zip_10464',
 'zip_10465',
 'zip_10466',
 'zip_10467',
 'zip_10468',
 'zip_10469',
 'zip_

## Scaler

In [10]:
scaler=pickle.load(open('scaler.pkl','rb'))

Apply scaler to numeric columns

In [11]:
part_c=pd.DataFrame.from_records(
    scaler.transform(np.array([[int(predict[1]),float(predict[2]),float(predict[3]),float(predict[5]),float(predict[6])]])),
    columns=(['beds', 'baths', 'sq_ft', 'Unemployment_rate', 'income_rate'])
)

In [12]:
part_c

beds     baths     sq_ft  Unemployment_rate  income_rate
0  0.361618  0.854592 -0.153198          -0.286261     -0.69863

In [13]:
#pickle.dump(classifier, open('linearreg.pkl','wb'))

## Model Linear regression

In [14]:
from sklearn.linear_model import LinearRegression
model_input = pd.concat([part_c,part_a,part_b], axis="columns")
model_input

beds     baths     sq_ft  Unemployment_rate  income_rate  \
0  0.361618  0.854592 -0.153198          -0.286261     -0.69863   

   boro_Kings County                                        \
0                                                0.0         

   boro_New York County                                     \
0                                                0.0         

   boro_Queens County                                       \
0                                                1.0         

   boro_Richmond County                                     zip_10002  ...  \
0                                                0.0              0.0  ...   

   zip_11426  zip_11427  zip_11428  zip_11429  zip_11430  zip_11432  \
0        0.0        0.0        0.0        0.0        0.0        0.0   

   zip_11433  zip_11434  zip_11435  zip_11436  
0        0.0        0.0        0.0        0.0  

[1 rows x 167 columns]

In [15]:
list()

[]

In [16]:
test=np.array([[-0.63621744,  0.16800858, -0.18531993, -0.09751796,  1.50024087,
        0.        ,  1.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ]])

Load model

In [26]:
classifier=pickle.load(open('linearreg.pkl','rb'))

In [27]:
classifier.predict(model_input.values)

array([-1.37073027e+14])

In [28]:
classifier.predict(test)

array([-6.83792742e+09])

In [29]:
list(model_input.columns)

['beds',
 'baths',
 'sq_ft',
 'Unemployment_rate',
 'income_rate',
 'boro_Kings County                                      ',
 'boro_New York County                                   ',
 'boro_Queens County                                     ',
 'boro_Richmond County                                   ',
 'zip_10002',
 'zip_10003',
 'zip_10004',
 'zip_10005',
 'zip_10006',
 'zip_10007',
 'zip_10009',
 'zip_10010',
 'zip_10011',
 'zip_10012',
 'zip_10013',
 'zip_10014',
 'zip_10016',
 'zip_10017',
 'zip_10018',
 'zip_10019',
 'zip_10021',
 'zip_10022',
 'zip_10023',
 'zip_10024',
 'zip_10025',
 'zip_10026',
 'zip_10027',
 'zip_10028',
 'zip_10029',
 'zip_10030',
 'zip_10031',
 'zip_10032',
 'zip_10033',
 'zip_10034',
 'zip_10035',
 'zip_10036',
 'zip_10037',
 'zip_10038',
 'zip_10039',
 'zip_10040',
 'zip_10044',
 'zip_10065',
 'zip_10075',
 'zip_10128',
 'zip_10280',
 'zip_10301',
 'zip_10302',
 'zip_10303',
 'zip_10304',
 'zip_10305',
 'zip_10306',
 'zip_10307',
 'zip_10308',
 'zip_1

In [30]:
from joblib import dump, load

classifier2=load('liregjob.joblib') 

In [31]:
classifier2.predict(test)

array([-6.83792742e+09])

In [32]:
print(classifier.coef_)

[-3.30954159e+04  3.56369375e+05  1.14177150e+05 -8.89217029e+17
  4.92811598e+18  6.47408719e+17 -1.15841421e+19 -9.15821412e+17
 -5.12128228e+18 -9.70416000e+05 -2.87344000e+05 -2.48520000e+04
 -9.56288000e+05 -1.06021800e+06  3.02976000e+05 -7.97888000e+05
 -2.78976000e+05 -4.86144000e+05  4.70656000e+05  4.67456000e+05
 -4.40960000e+04 -9.79456000e+05 -9.74848000e+05  1.12352000e+05
 -3.54304000e+05 -5.70944000e+05 -7.04208000e+05 -8.62016000e+05
 -2.94304000e+05 -1.00377600e+06 -1.13152000e+06 -9.96864000e+05
 -6.23996000e+05 -1.01824000e+06 -1.23923200e+06 -1.10694400e+06
 -1.13408000e+06 -1.12166400e+06 -1.38203200e+06 -7.42048000e+05
 -9.18688000e+05 -1.29385600e+06 -1.00460800e+06 -1.42080000e+06
 -1.29836800e+06 -1.34396800e+06 -1.45819200e+06 -9.17240000e+05
 -1.58912000e+06 -1.11239800e+06 -4.96656000e+05 -4.88720000e+05
 -4.82528000e+05 -5.38528000e+05 -5.66992000e+05 -5.24592000e+05
 -4.25344000e+05 -5.20272000e+05 -5.23904000e+05 -5.90688000e+05
 -4.89536000e+05 -4.69920

In [33]:
classifier.intercept_

4.1040664176403267e+18

In [34]:
[0,1,]

[0, 1]

In [35]:
coefs = np.expand_dims(np.array(classifier.coef_),1)
coefs.shape

(167, 1)

In [37]:
test.shape

(1, 167)

In [43]:
(test@coefs)+classifier.intercept_

array([[-6.83792742e+09]])

In [40]:
test

array([[-0.63621744,  0.16800858, -0.18531993, -0.09751796,  1.50024087,
         0.        ,  1.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0. 

In [41]:
coefs

array([[-3.30954159e+04],
       [ 3.56369375e+05],
       [ 1.14177150e+05],
       [-8.89217029e+17],
       [ 4.92811598e+18],
       [ 6.47408719e+17],
       [-1.15841421e+19],
       [-9.15821412e+17],
       [-5.12128228e+18],
       [-9.70416000e+05],
       [-2.87344000e+05],
       [-2.48520000e+04],
       [-9.56288000e+05],
       [-1.06021800e+06],
       [ 3.02976000e+05],
       [-7.97888000e+05],
       [-2.78976000e+05],
       [-4.86144000e+05],
       [ 4.70656000e+05],
       [ 4.67456000e+05],
       [-4.40960000e+04],
       [-9.79456000e+05],
       [-9.74848000e+05],
       [ 1.12352000e+05],
       [-3.54304000e+05],
       [-5.70944000e+05],
       [-7.04208000e+05],
       [-8.62016000e+05],
       [-2.94304000e+05],
       [-1.00377600e+06],
       [-1.13152000e+06],
       [-9.96864000e+05],
       [-6.23996000e+05],
       [-1.01824000e+06],
       [-1.23923200e+06],
       [-1.10694400e+06],
       [-1.13408000e+06],
       [-1.12166400e+06],
       [-1.3